+include managed.css.slang

.sooraat
	width		600px
	height		1000px
	margin		0 auto
	border		1px solid @secondary
.sooraat .row
	width				600px
	height				333px
//	background-size		50%
//	background-position	10% 50%
	background-size		cover
	background-position	100%
	background-repeat	no-repeat
.sooraat .row .matn
	font-size			350%
	text-shadow			0 0 15px @primary, 0 0 15px @primary

//if max-width = 640px
//	.maHdood
//		overflow			auto
//		max-height			70vh








